// <auto-generated />
using DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseContext.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250418200145_Added-symoblicpoint-data")]
    partial class Addedsymoblicpointdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("DatabaseContext.Models.Agv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgvId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Agvs");
                });

            modelBuilder.Entity("DatabaseContext.Models.SymbolicPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SymbolicPointName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("x")
                        .HasColumnType("REAL");

                    b.Property<float>("y")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("SymbolicPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
